[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Erigon"
authors = [{name = "Bloxster", email = "jerryblunt2@gmail.com"}]
dynamic = ["version", "description"]
